version: '2.1'

services:
  web:
    image: webappdemo.web
    build:
      context: .\Web\WebAppDemo.Web
      dockerfile: Dockerfile
    networks:
      default:
        ipv4_address: 172.26.64.10
        aliases:
          - web

  api:
    image: webappdemo.api
    build:
      context: .\Api\WebAppDemo.Api
      dockerfile: Dockerfile
    networks:
      default:
        ipv4_address: 172.26.64.20
        aliases:
          - api
    depends_on: 
        sqlserver:
          condition: service_healthy

  sqlserver:
    image: microsoft/mssql-server-windows-express
    container_name: sqlserver
    ports: 
        - "1433:1433"
    environment: 
        sa_password: P@ssw0rd
        accept_eula: Y
        #attach_dbs: "[{'dbName':'trunk','dbFiles':['c:\\\\Databases\\\\trunk.mdf','c:\\\\Databases\\\\trunk_Log.ldf']}]"
    healthcheck:
      test: "exit 0"
    networks:
      default:
        ipv4_address: 172.26.64.30
        aliases:
        - sqlserver